import sys
from contextlib import contextmanager
from pathlib import Path
from uuid import uuid4

import pytest
from fastapi.testclient import TestClient

BACKEND_SRC = Path(__file__).resolve().parents[1] / "src"
sys.path.insert(0, str(BACKEND_SRC))

from mininode_api.main import create_app  # noqa: E402
from mininode_api.services import learn_feedback  # noqa: E402


@pytest.fixture
def client(monkeypatch):
    monkeypatch.delenv("API_KEY", raising=False)
    monkeypatch.delenv("API_KEYS", raising=False)
    app = create_app()
    app.state.learn_feedback_ready = True
    return TestClient(app)


def test_initialization_uses_idempotent_learn_schema_and_seed(monkeypatch):
    executions = []

    class Cursor:
        def execute(self, statement, params=None):
            executions.append((statement, params))

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

    class Connection:
        def cursor(self):
            return Cursor()

    @contextmanager
    def connection():
        yield Connection()

    monkeypatch.setattr(learn_feedback, "_connection", connection)
    learn_feedback.initialize_database()
    learn_feedback.initialize_database()

    assert len(executions) == 2
    sql = executions[0][0]
    assert "CREATE SCHEMA IF NOT EXISTS learn" in sql
    assert "CREATE TABLE IF NOT EXISTS learn.content" in sql
    assert "CREATE TABLE IF NOT EXISTS learn.feedback" in sql
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in sql
    assert "content_key TEXT UNIQUE NOT NULL" in sql
    assert "slug TEXT UNIQUE NOT NULL" in sql
    assert "REFERENCES learn.content(id)" in sql
    assert "ON CONFLICT (content_key) DO NOTHING" in sql
    assert learn_feedback.BRIEF_001_CONTENT_KEY in sql
    assert learn_feedback.BRIEF_003_CONTENT_KEY in sql
    assert "'/learn/briefs/001-nueva-autoridad-de-datos'" in sql
    assert "'/learn/briefs/003-datos-personales'" in sql
    assert "'brief'" in sql
    assert "CREATE INDEX IF NOT EXISTS learn_feedback_content_id_idx" in sql
    assert "public.learn_" not in sql


def test_create_feedback_snapshots_content_identity_and_version(monkeypatch):
    feedback_id = uuid4()
    statements = []

    class Cursor:
        def execute(self, statement, params=None):
            statements.append((" ".join(statement.split()), params))

        def fetchone(self):
            return (41, 3)

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

    @contextmanager
    def connection():
        yield type("Connection", (), {"cursor": lambda self: Cursor()})()

    monkeypatch.setattr(learn_feedback, "_connection", connection)
    monkeypatch.setattr(learn_feedback, "uuid4", lambda: feedback_id)

    result = learn_feedback.create_feedback(content_key=learn_feedback.CONTENT_KEY, rating=4)

    assert result == feedback_id
    assert statements[0][1] == (learn_feedback.CONTENT_KEY,)
    assert "FROM learn.content" in statements[0][0]
    assert statements[1][1] == (feedback_id, 41, 3, 4)
    assert "INSERT INTO learn.feedback" in statements[1][0]
    assert "content_key" not in statements[1][0]


def fake_update_connection(monkeypatch, current=(3, None)):
    statements = []

    class Cursor:
        def execute(self, statement, params=None):
            statements.append((" ".join(statement.split()), params))

        def fetchone(self):
            return current

        def __enter__(self):
            return self

        def __exit__(self, *args):
            pass

    @contextmanager
    def connection():
        yield type("Connection", (), {"cursor": lambda self: Cursor()})()

    monkeypatch.setattr(learn_feedback, "_connection", connection)
    return statements


def test_patch_updates_same_row_and_only_updated_at(monkeypatch):
    statements = fake_update_connection(monkeypatch)
    feedback_id = uuid4()

    learn_feedback.update_feedback(feedback_id, rating=2, comment="Más ejemplos")

    assert len(statements) == 2
    update_sql, params = statements[1]
    assert "UPDATE learn.feedback" in update_sql
    assert "rating = %s" in update_sql and "comment = %s" in update_sql
    assert "updated_at = CURRENT_TIMESTAMP" in update_sql
    assert "created_at" not in update_sql
    assert "INSERT" not in update_sql
    assert params == [2, "Más ejemplos", feedback_id]


@pytest.mark.parametrize("rating", [1, 2, 3, 4, 5])
def test_comments_are_allowed_for_every_rating(monkeypatch, rating):
    feedback_id = uuid4()
    statements = fake_update_connection(monkeypatch, current=(rating, "Comentario previo"))
    learn_feedback.update_feedback(feedback_id, rating=rating, comment="Faltó detalle")
    assert len(statements) == 2


def test_rating_change_preserves_topic_and_comment(monkeypatch):
    statements = fake_update_connection(monkeypatch, current=(2, "Comentario previo"))
    learn_feedback.update_feedback(uuid4(), rating=5)
    update_sql, params = statements[1]
    assert "rating = %s" in update_sql
    assert "topic = %s" not in update_sql and "comment = %s" not in update_sql
    assert params[0] == 5


def test_topic_change_preserves_rating(monkeypatch):
    statements = fake_update_connection(monkeypatch, current=(4, None))
    learn_feedback.update_feedback(uuid4(), topic="security")
    update_sql, params = statements[1]
    assert "topic = %s" in update_sql and "rating = %s" not in update_sql
    assert params[0] == "security"


def test_get_feedback_returns_minimum_state(monkeypatch):
    statements = fake_update_connection(monkeypatch, current=(4, "security", "Más ejemplos"))
    feedback_id = uuid4()
    assert learn_feedback.get_feedback(feedback_id) == (4, "security", "Más ejemplos")
    sql, params = statements[0]
    assert "SELECT rating, topic, comment FROM learn.feedback" in sql
    assert params == (feedback_id,)


def test_rating_is_created_with_content_key(client, monkeypatch):
    feedback_id = uuid4()
    calls = []
    monkeypatch.setattr(
        learn_feedback,
        "create_feedback",
        lambda **values: calls.append(values) or feedback_id,
    )

    response = client.post(
        "/learn/feedback",
        json={"content_key": learn_feedback.CONTENT_KEY, "rating": 5},
    )

    assert response.status_code == 201
    assert response.json() == {"feedback_id": str(feedback_id)}
    assert calls == [{"content_key": learn_feedback.CONTENT_KEY, "rating": 5}]


def test_get_existing_feedback_exposes_only_restorable_state(client, monkeypatch):
    feedback_id = uuid4()
    monkeypatch.setattr(learn_feedback, "get_feedback", lambda value: (4, "security", "Más ejemplos"))
    response = client.get(f"/learn/feedback/{feedback_id}")
    assert response.status_code == 200
    assert response.json() == {"rating": 4, "topic": "security", "comment": "Más ejemplos"}
    assert "has_comment" not in response.json()


def test_get_existing_feedback_exposes_null_without_comment(client, monkeypatch):
    feedback_id = uuid4()
    monkeypatch.setattr(learn_feedback, "get_feedback", lambda value: (4, "security", None))
    response = client.get(f"/learn/feedback/{feedback_id}")
    assert response.status_code == 200
    assert response.json() == {"rating": 4, "topic": "security", "comment": None}


def test_get_missing_feedback_returns_404(client, monkeypatch):
    def missing(_feedback_id):
        raise learn_feedback.FeedbackNotFoundError("Feedback not found")

    monkeypatch.setattr(learn_feedback, "get_feedback", missing)
    assert client.get(f"/learn/feedback/{uuid4()}").status_code == 404


@pytest.mark.parametrize("rating", [0, 6, 1.5, "five"])
def test_rating_must_be_an_integer_between_one_and_five(client, rating):
    response = client.post(
        "/learn/feedback",
        json={"content_key": learn_feedback.CONTENT_KEY, "rating": rating},
    )
    assert response.status_code == 422


def test_api_no_longer_accepts_ebook_id_or_personal_fields(client):
    for payload in (
        {"ebook_id": learn_feedback.CONTENT_KEY, "rating": 4},
        {"content_key": learn_feedback.CONTENT_KEY, "rating": 4, "email": "person@example.com"},
    ):
        assert client.post("/learn/feedback", json=payload).status_code == 422


@pytest.mark.parametrize("topic", ["business_data", "website_forms", "files", "policies", "security", "new_law"])
def test_topic_codes_are_accepted(client, monkeypatch, topic):
    calls = []
    monkeypatch.setattr(learn_feedback, "update_feedback", lambda *args, **kwargs: calls.append(kwargs))
    response = client.patch(f"/learn/feedback/{uuid4()}", json={"topic": topic})
    assert response.status_code == 204
    assert calls == [{"topic": topic}]


def test_arbitrary_topic_is_rejected(client):
    response = client.patch(f"/learn/feedback/{uuid4()}", json={"topic": "Seguridad"})
    assert response.status_code == 422


def test_comment_length_and_empty_patch_are_rejected(client):
    assert client.patch(f"/learn/feedback/{uuid4()}", json={"comment": "a" * 501}).status_code == 422
    assert client.patch(f"/learn/feedback/{uuid4()}", json={}).status_code == 422


def test_unified_patch_passes_rating_topic_and_comment(client, monkeypatch):
    calls = []
    feedback_id = uuid4()
    monkeypatch.setattr(learn_feedback, "update_feedback", lambda *args, **kwargs: calls.append((args, kwargs)))

    response = client.patch(
        f"/learn/feedback/{feedback_id}",
        json={"rating": 2, "topic": "security", "comment": "Más ejemplos"},
    )

    assert response.status_code == 204
    assert calls == [((feedback_id,), {"rating": 2, "topic": "security", "comment": "Más ejemplos"})]


def test_database_unavailable_is_explicit(client):
    client.app.state.learn_feedback_ready = False
    response = client.post(
        "/learn/feedback", json={"content_key": learn_feedback.CONTENT_KEY, "rating": 3}
    )
    assert response.status_code == 503


def test_startup_failure_is_logged_without_breaking_health(monkeypatch, caplog):
    monkeypatch.delenv("DATABASE_URL", raising=False)
    app = create_app()
    with caplog.at_level("ERROR"), TestClient(app) as startup_client:
        assert startup_client.get("/health").status_code == 200
        assert startup_client.post(
            "/learn/feedback",
            json={"content_key": learn_feedback.CONTENT_KEY, "rating": 3},
        ).status_code == 503
    assert "Learn feedback database initialization failed" in caplog.text
    assert "postgres" not in caplog.text.lower()
