"""PostgreSQL initialization and persistence for anonymous Learn feedback."""

from __future__ import annotations

import os
from contextlib import contextmanager
from typing import Iterator
from uuid import UUID, uuid4

import psycopg

CONTENT_KEY = "001-privacidad-para-pequenos-negocios"
BRIEF_001_CONTENT_KEY = "brief-001-nueva-autoridad-de-datos"
UNSET = object()

INITIALIZE_SQL = """
CREATE SCHEMA IF NOT EXISTS learn;

CREATE TABLE IF NOT EXISTS learn.content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_key TEXT UNIQUE NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    content_type TEXT NOT NULL,
    title TEXT NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('draft', 'published', 'archived')),
    current_version INTEGER NOT NULL CHECK (current_version >= 1),
    published_at TIMESTAMPTZ NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS learn.feedback (
    id UUID PRIMARY KEY,
    content_id BIGINT NOT NULL REFERENCES learn.content(id),
    content_version INTEGER NOT NULL CHECK (content_version >= 1),
    rating SMALLINT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    topic TEXT NULL,
    comment VARCHAR(500) NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS learn_feedback_content_id_idx
    ON learn.feedback(content_id);

INSERT INTO learn.content (
    content_key, slug, content_type, title, status, current_version, published_at
) SELECT
    '001-privacidad-para-pequenos-negocios',
    '/learn/privacy',
    'micro_ebook',
    'Privacidad para pequeños negocios',
    'published',
    1,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM learn.content
    WHERE content_key = '001-privacidad-para-pequenos-negocios'
)
ON CONFLICT (content_key) DO NOTHING;

INSERT INTO learn.content (
    content_key, slug, content_type, title, status, current_version, published_at
) SELECT
    'brief-001-nueva-autoridad-de-datos',
    '/learn/briefs/001-nueva-autoridad-de-datos',
    'brief',
    'Nueva autoridad de datos',
    'published',
    1,
    CURRENT_TIMESTAMP
WHERE NOT EXISTS (
    SELECT 1 FROM learn.content
    WHERE content_key = 'brief-001-nueva-autoridad-de-datos'
)
ON CONFLICT (content_key) DO NOTHING;
"""


class FeedbackNotFoundError(Exception):
    """The requested content or feedback row does not exist."""


def _database_url() -> str:
    database_url = os.getenv("DATABASE_URL")
    if not database_url:
        raise RuntimeError("DATABASE_URL is not configured")
    return database_url


@contextmanager
def _connection() -> Iterator[psycopg.Connection]:
    with psycopg.connect(_database_url()) as connection:
        yield connection


def initialize_database() -> None:
    """Create the Learn schema and seed once during application startup."""
    with _connection() as connection, connection.cursor() as cursor:
        cursor.execute(INITIALIZE_SQL)


def create_feedback(*, content_key: str, rating: int) -> UUID:
    feedback_id = uuid4()
    with _connection() as connection, connection.cursor() as cursor:
        cursor.execute(
            "SELECT id, current_version FROM learn.content WHERE content_key = %s",
            (content_key,),
        )
        content = cursor.fetchone()
        if content is None:
            raise FeedbackNotFoundError("Content not found")
        cursor.execute(
            """
            INSERT INTO learn.feedback (id, content_id, content_version, rating)
            VALUES (%s, %s, %s, %s)
            """,
            (feedback_id, content[0], content[1], rating),
        )
    return feedback_id


def get_feedback(feedback_id: UUID) -> tuple[int, str | None, str | None]:
    """Return only the fields needed to restore the anonymous feedback UI."""
    with _connection() as connection, connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT rating, topic, comment
            FROM learn.feedback
            WHERE id = %s
            """,
            (feedback_id,),
        )
        feedback = cursor.fetchone()
        if feedback is None:
            raise FeedbackNotFoundError("Feedback not found")
        return feedback


def update_feedback(
    feedback_id: UUID,
    *,
    rating: int | object = UNSET,
    topic: str | None | object = UNSET,
    comment: str | None | object = UNSET,
) -> None:
    with _connection() as connection, connection.cursor() as cursor:
        cursor.execute(
            "SELECT 1 FROM learn.feedback WHERE id = %s FOR UPDATE",
            (feedback_id,),
        )
        current = cursor.fetchone()
        if current is None:
            raise FeedbackNotFoundError("Feedback not found")

        assignments: list[str] = []
        values: list[object] = []
        for column, value in (("rating", rating), ("topic", topic), ("comment", comment)):
            if value is not UNSET:
                assignments.append(f"{column} = %s")
                values.append(value)
        assignments.append("updated_at = CURRENT_TIMESTAMP")
        values.append(feedback_id)
        cursor.execute(
            f"UPDATE learn.feedback SET {', '.join(assignments)} WHERE id = %s",
            values,
        )
